import json
from fastapi import FastAPI  #, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import List
from langchain_core.messages import HumanMessage, AIMessage

# Import our compiled LangGraph agent
from src.agent.graph import app as agent_app

# 1. Initialize the FastAPI Server
app = FastAPI(
    title="OmniRouter Streaming API Agent",
    description="Enterprise RAG Agent powered by LangGraph and FastAPI",
    version="1.0.1"
)

# 2. Define our Request Schema using Pydantic
class ChatRequest(BaseModel):
    query: str

app = FastAPI(title="OmniRouter Streaming API")

class ChatRequest(BaseModel):
    query: str

async def stream_generator(query: str):
    """
    An async generator that yields tokens from the LangGraph agent 
    in a format compatible with Server-Sent Events (SSE).
    """
    initial_state = {"messages": [HumanMessage(content=query)]}

    # .astream_events is the key to deep-access streaming in LangChain/LangGraph
    async for event in agent_app.astream_events(initial_state, version="v1"):
        kind = event["event"]

        # We are looking for the 'on_chat_model_stream' event
        # This triggers every time a new token is generated by the LLM
        if kind == "on_chat_model_stream":
            content = event["data"]["chunk"].content
            if content:
                # SSE format requires the "data: " prefix
                yield f"data: {json.dumps({'token': content})}\n\n"

@app.post("/chat/stream")
async def chat_streaming_endpoint(request: ChatRequest):
    return StreamingResponse(
        stream_generator(request.query), 
        media_type="text/event-stream"
    )